import { Document, Page, Text, View, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Note: In a real environment, you'd register custom fonts here.
// Font.register({ family: 'Inter', src: '...' });

const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    paddingBottom: 20,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoPlaceholder: {
    width: 40,
    height: 40,
    backgroundColor: '#10b981',
    borderRadius: 8,
    marginRight: 10,
  },
  companyName: {
    fontSize: 20,
    fontWeight: 'black',
    color: '#0f172a',
  },
  reportTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  summaryGrid: {
    flexDirection: 'row',
    marginBottom: 30,
    gap: 10,
  },
  summaryCard: {
    flex: 1,
    padding: 15,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
  },
  summaryLabel: {
    fontSize: 8,
    color: '#64748b',
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0f172a',
  },
  table: {
    display: 'flex',
    width: 'auto',
    marginTop: 20,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomColor: '#f1f5f9',
    borderBottomWidth: 1,
    minHeight: 30,
    alignItems: 'center',
  },
  tableHeader: {
    backgroundColor: '#f8fafc',
    borderBottomColor: '#e2e8f0',
    borderBottomWidth: 2,
  },
  tableCol: {
    flex: 1,
    padding: 5,
  },
  tableCell: {
    fontSize: 9,
    color: '#334155',
  },
  tableHeaderCell: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#64748b',
    textTransform: 'uppercase',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 8,
    color: '#94a3b8',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  }
});

interface CustomerReportProps {
  customers: any[];
}

export const CustomerReport = ({ customers }: CustomerReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View style={styles.logoContainer}>
          <View style={styles.logoPlaceholder} />
          <View>
            <Text style={styles.companyName}>EYE ADOM</Text>
            <Text style={{ fontSize: 8, color: '#64748b' }}>SUSU & SAVINGS</Text>
          </View>
        </View>
        <Text style={styles.reportTitle}>Customer Directory</Text>
      </View>

      <View style={styles.summaryGrid}>
        <View style={styles.summaryCard}>
          <Text style={styles.summaryLabel}>Total Members</Text>
          <Text style={styles.summaryValue}>{customers.length}</Text>
        </View>
        <View style={styles.summaryCard}>
          <Text style={styles.summaryLabel}>Active Period</Text>
          <Text style={styles.summaryValue}>{new Date().toLocaleDateString()}</Text>
        </View>
      </View>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <View style={[styles.tableCol, { flex: 0.5 }]}>
            <Text style={styles.tableHeaderCell}>ID</Text>
          </View>
          <View style={[styles.tableCol, { flex: 2 }]}>
            <Text style={styles.tableHeaderCell}>Customer Name</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableHeaderCell}>Phone</Text>
          </View>
          <View style={styles.tableCol}>
            <Text style={styles.tableHeaderCell}>Type</Text>
          </View>
        </View>

        {customers.map((c, index) => (
          <View key={c.customer_number} style={styles.tableRow}>
            <View style={[styles.tableCol, { flex: 0.5 }]}>
              <Text style={styles.tableCell}>#{c.customer_number}</Text>
            </View>
            <View style={[styles.tableCol, { flex: 2 }]}>
              <Text style={styles.tableCell}>{c.first_name} {c.surname}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{c.phone_number || 'N/A'}</Text>
            </View>
            <View style={styles.tableCol}>
              <Text style={styles.tableCell}>{c.customer_type_name || 'Regular'}</Text>
            </View>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        Generated by MIMS Platform on {new Date().toLocaleString()} | Eye Adom Susu & Savings
      </Text>
    </Page>
  </Document>
);
